name: CD Pipeline

on:
    push:
        branches:
            - main
            - qa
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest

        # Dynamically choose GitHub Environment based on branch
        environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'qa' && 'qa' || 'dev' }}

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Run tests
          env: 
            APP_ENV: ${{ github.ref_name }}
          run: pytest tests

        - name: Deploy to Streamlit Cloud
          run: |
            echo "🚀 Deployed to ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'qa' && 'qa' || 'dev' }} environment => ${{ secrets.APP_URL }}"
