name: CD Pipeline

on:
    push:
        branches: [dev, qa, main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        # Dynamically choose GitHub Environment based on branch
        environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'qa' && 'qa' || 'dev' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13.x'

            - name: Install app dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            # Nothing else to do here since Streamlit Cloud will auto-deploy the branch
            # This is just a simulated deploy, showing the different destinations on Streamlit Cloud
            # for each environment
            - run: echo "🚀 App deployed to ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'qa' && 'qa' || 'dev' }} environment => ${{ vars.APP_URL }}"
